# Generated by Django 4.2 on 2026-03-24 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CASHIER', 'Cashier'), ('MANAGER', 'Store Manager')], default='CASHIER', max_length=15)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pin', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'PIN must be 4 digits.')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
