# Generated by Django 4.2 on 2026-03-24 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'PIN must be 4 digits.')]),
        ),
    ]
